grpc:
  server:
    port: 50051

datasources:
  #default:
  #url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
  #username: ${JDBC_USER:sa}
  #password: ${JDBC_PASSWORD:""}
  #driverClassName: ${JDBC_DRIVER:org.h2.Driver}
  default:
    url: jdbc:postgresql://localhost:5432/grpc
    driverClassName: org.postgresql.Driver
    username: sudo_kishor
    password: ronaldo
#end::datasource[]
---
#tag::jpa[]
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
#end::jpa[]